// --- Postgres ENUM types ---

export type CampaignStatus = 'available' | 'not_available';
export type CouponStatus = 'available' | 'not_available';
export type UserRole = 'user' | 'admin';

// Table interfaces are generated by Kysely (npm run generate)
